### ISSUE TITLE
troubleshooting xnat_downloader on argon

### ISSUE THREAD

**Issue by bmv243** [NeuroimagingUIowa/xnat_downloader#49]
We are having trouble mounting our servers and the argon home directory in our .sh file to run on argon. We also tried to get around the password for the xnat server by creating a .json file on the argon home directory with credentials and server call.

*We recently changed server directories so certain automated pipelines have been stuck

### **.sh file commands**

> `#!/usr/bin/env bash
> 
> #$ -pe smp 16
> #$ -q UI
> #$ -m bea
> #$ -M bryan-madero@uiowa.edu
> #$ -e /Shared/vosslabhpc/Projects/BikeExtend/3-Experiment/2-Data/BIDS/code/
> 
> OMP_NUM_THREADS=10
> 
> singularity run --cleanenv -B /Shared/vosslabhpc/Projects/BikeExtend/3-Experiment/2-Data/BIDS:/out \
>         /Shared/vosslabhpc/UniversalSoftware/SingularityContainers/xnat_downloader-v0.2.8.sif \
>         -i /Shared/vosslabhpc/Projects/BikeExtend/3-Experiment/2-Data/BIDS/code/extend_download_config.json \
>         -c /Users/bmadero/xnat_pass_config.json
> `
> 

### **The error output we get is**

> `Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xnat_downloader", line 11, in <module>
    load_entry_point('xnat-downloader==0.1', 'console_scripts', 'xnat_downloader')()
  File "/usr/local/miniconda/lib/python2.7/site-packages/xnat_downloader-0.1-py2.7.egg/xnat_downloader/cli/run.py", line 615, in main
    central = Interface(config=opts.config)
  File "/usr/local/miniconda/lib/python2.7/site-packages/pyxnat/core/interfaces.py", line 165, in __init__
    self.load_config(config)
  File "/usr/local/miniconda/lib/python2.7/site-packages/pyxnat/core/interfaces.py", line 470, in load_config
    config = json.load(fp)
  File "/usr/local/miniconda/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/miniconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/miniconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/miniconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

1. Are we mounting the two server correctly so that argon and xnat can properly find these files?
2. Is having the `xnat_pass_config.json` on the argon home directory helpful?
    - which consists of `{"password": "testPass", "user": "xnatTest", "server": "https://central.xnat.org"}`

**Comment by jdkent** [comment]
It looks correct to me, here is what I would do to diagnose the issue:

enter the singularity container:
`singularity  shell --cleanenv /Shared/vosslabhpc/UniversalSoftware/SingularityContainers/xnat_downloader-v0.2.8.sif`
(should see this on your terminal `Singularity>`)

Check to see if the config file exists:
`ls /Users/bmadero/xnat_pass_config.json`
(if it exists you should see the name of the file printed back to you)

If it exists, check to see if python can read the json file:
```
python
>>> import json
>>> with open("/Users/bmadero/xnat_pass_config.json", "r") as f:
           data = json.load(f)
```
If that fails, then there is something incorrect about the json file, and you can use [JSONLinter](https://jsonlint.com/) to help 
identify the problem.

let me know if this helps identify the issue.

**Comment by bmv243** [comment]
I was able to progress a little further, my .json file was not formatted correctly. Though now I get a new error:

> `Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xnat_downloader", line 11, in <module>
    load_entry_point('xnat-downloader==0.1', 'console_scripts', 'xnat_downloader')()
  File "/usr/local/miniconda/lib/python2.7/site-packages/xnat_downloader-0.1-py2.7.egg/xnat_downloader/cli/run.py", line 615, in main
    central = Interface(config=opts.config)
  File "/usr/local/miniconda/lib/python2.7/site-packages/pyxnat/core/interfaces.py", line 165, in __init__
    self.load_config(config)
  File "/usr/local/miniconda/lib/python2.7/site-packages/pyxnat/core/interfaces.py", line 484, in load_config
    raise Exception('Configuration file does not exist.')
Exception: Configuration file does not exist.`

Not sure if this also matters but in the `/Users/bmadero/xnat_pass_config.json` file we've changed the server to `"server": "https://rpacs.iibi.uiowa.edu/xnat"` as it is set up in the other config file.

**Comment by mattsodoma** [comment]
I got it working using the above, will work with Bryan to troubleshoot. Thanks James!
